// EncryptTool/Program.cs
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json; // (NuGet: Newtonsoft.Json 필요)
using Npgsql;          // (NuGet: Npgsql 필요)
using ConnectInfo;     // (참조: ConnectInfo.dll)

namespace EncryptTool
{
    /// <summary>
    /// FTP(또는 Upload API) 접속 정보를 직렬화하기 위한 DTO
    /// (ConnectInfo.dll의 FtpConfig와 동일 구조)
    /// </summary>
    internal class FtpConfig
    {
        public string Host { get; set; }
        public int Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("--- ITM Agent Connection.ini 암호화 생성 도구 (Rocky Linux 호환) ---");
            Console.WriteLine("배포용 Connection.ini 파일을 생성합니다.");

            // =================================================================================
            // [STEP 1] 신규 구축한 Rocky Linux VM 정보를 아래 변수에 입력하세요.
            // =================================================================================
            
            // 1. 데이터베이스 연결 정보 (PostgreSQL)
            string dbHost = "192.168.x.x";      // [수정필요] Rocky Linux VM의 IP 주소
            string dbPort = "5432";             // (기본값: 5432)
            string dbUser = "postgres";         // [수정필요] DB 계정 (예: postgres)
            string dbPass_PLAIN = "your_db_password"; // [수정필요] DB 암호 (평문)
            string dbName = "ITM_Vision";       // [수정필요] DB 이름

            // 2. 파일 업로드 API 정보 (기존 FTP 대신 API 정보로 활용)
            // Agent가 이 정보를 사용하여 Upload API 서버 위치를 파악합니다.
            string ftpHost = "192.168.x.x";     // [수정필요] Rocky Linux VM의 IP 주소 (보통 DB와 동일)
            
            // ★중요: Upload API가 8082 포트를 사용하므로, 21 대신 8082로 변경 권장
            // (Agent 내부 로직에 따라 이 포트 값을 무시하고 8082를 강제할 수도 있지만, 명시적으로 맞추는 것이 좋음)
            string ftpPort = "8082";            
            
            string ftpUser = "itm_api_user";    // (API에서 인증을 사용하지 않는다면 임의 값)
            string ftpPass_PLAIN = "api_pass";  // (API에서 인증을 사용하지 않는다면 임의 값)

            // =================================================================================

            try
            {
                // 2. DB 연결 문자열 (평문) 생성
                var csBuilder = new NpgsqlConnectionStringBuilder
                {
                    Host = dbHost,
                    Port = int.Parse(dbPort ?? "5432"),
                    Username = dbUser,
                    Password = dbPass_PLAIN,
                    Database = dbName,
                    Encoding = "UTF8",
                    SslMode = SslMode.Disable, // 내부망이므로 SSL 끔 (필요시 Prefer로 변경)
                    SearchPath = "public"
                };
                string dbConfigString = csBuilder.ConnectionString;

                // 3. FTP(API) 설정 (JSON 평문) 생성
                var ftpConfig = new FtpConfig
                {
                    Host = ftpHost,
                    Port = int.Parse(ftpPort ?? "8082"),
                    Username = ftpUser,
                    Password = ftpPass_PLAIN
                };
                string ftpConfigString = JsonConvert.SerializeObject(ftpConfig);

                // 4. 각각 공용 키(AES)로 암호화
                // (AgentCryptoConfig.AES_COMMON_KEY는 ConnectInfo.dll에 정의되어 있다고 가정)
                string encryptedDbConfig = EncryptAES(dbConfigString, AgentCryptoConfig.AES_COMMON_KEY);
                string encryptedFtpConfig = EncryptAES(ftpConfigString, AgentCryptoConfig.AES_COMMON_KEY);

                // 5. 새로운 Connection.ini 파일 내용 생성
                StringBuilder sb = new StringBuilder();
                sb.AppendLine("; ITM Agent Connection Settings (Encrypted by EncryptTool for Rocky VM)");
                sb.AppendLine($"; Created: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
                sb.AppendLine("; Do not edit this file manually.");
                sb.AppendLine();
                sb.AppendLine("[Database]");
                sb.AppendLine($"Config = {encryptedDbConfig}");
                sb.AppendLine();
                sb.AppendLine("[Ftps]");
                sb.AppendLine($"Config = {encryptedFtpConfig}");

                // 6. Connection.ini 파일로 저장
                // 실행 파일(exe)과 같은 폴더에 생성됨
                string outputPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Connection.ini");
                File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);

                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine($"\n[성공] 파일 생성 완료: {outputPath}");
                Console.ResetColor();
                Console.WriteLine("이 Connection.ini 파일을 Agent가 설치된 폴더에 덮어쓰기 하세요.");
            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine($"\n[오류] 암호화 또는 파일 생성 실패");
                Console.WriteLine(ex.Message);
                Console.ResetColor();
            }

            Console.WriteLine("\n엔터 키를 누르면 종료됩니다...");
            Console.ReadLine();
        }

        /// <summary>
        /// AES-256 CBC 암호화 (Cross-Platform 호환 Aes.Create 사용)
        /// </summary>
        private static string EncryptAES(string plainText, string keyString)
        {
            if (string.IsNullOrEmpty(plainText)) return "";

            // 1. 키 해시 (SHA256) -> 32바이트 키 생성
            byte[] keyBytes;
            using (var sha = SHA256.Create())
            {
                keyBytes = sha.ComputeHash(Encoding.UTF8.GetBytes(keyString));
            }

            // 2. Aes.Create() 사용 (기존 AesManaged 대신 표준 방식 사용)
            // 이렇게 하면 Windows/Linux 어디서든 호환됩니다.
            using (var aes = Aes.Create())
            {
                aes.Key = keyBytes;
                aes.Mode = CipherMode.CBC;
                aes.Padding = PaddingMode.PKCS7;

                // 3. 새 랜덤 IV (16바이트) 생성
                aes.GenerateIV();
                byte[] iv = aes.IV;

                // 4. 암호화 수행
                byte[] cipherBytes;
                using (var encryptor = aes.CreateEncryptor(aes.Key, aes.IV))
                using (var ms = new MemoryStream())
                {
                    using (var cs = new CryptoStream(ms, encryptor, CryptoStreamMode.Write))
                    using (var sw = new StreamWriter(cs))
                    {
                        sw.Write(plainText);
                    }
                    cipherBytes = ms.ToArray();
                }

                // 5. 최종 결과물: [16바이트 IV] + [암호문]
                byte[] fullCipher = new byte[iv.Length + cipherBytes.Length];
                Buffer.BlockCopy(iv, 0, fullCipher, 0, iv.Length);
                Buffer.BlockCopy(cipherBytes, 0, fullCipher, iv.Length, cipherBytes.Length);

                // 6. Base64로 변환하여 반환
                return Convert.ToBase64String(fullCipher);
            }
        }
    }
}
